jslint:
  options:
    anon:       false     # true, if the space may be omitted in anonymous function declarations
    bitwise:    false     # true, if bitwise operators should be allowed
    cap:        false     # true, if upper case HTML should be allowed
    continue:   false     # true, if the continuation statement should be tolerated
    css:        false     # true, if CSS workarounds should be tolerated
    debug:      false     # true, if debugger statements should be allowed
    eqeq:       true      # true, if == should be allowed
    es5:        false     # true, if ES5 syntax should be allowed
    evil:       false     # true, if eval should be allowed
    forin:      false     # true, if for in statements need not filter
    fragment:   false     # true, if HTML fragments should be allowed
    forvar:     false     # true, if for(var i ....) construction should be allowed
    newcap:     false     # true, if constructor names capitalization is ignored
    node:       false     # true, if Node.js globals should be predefined
    nomen:      true      # true, if names may have dangling _
    on:         false     # true, if HTML event handlers should be allowed
    plusplus:   true      # true, if increment/decrement should be allowed
    properties: false     # true, if all property names must be declared with /*properties*/
    regexp:     false     # true, if the . should be allowed in regexp literals
    undef:      true      # true, if variables can be declared out of order
    unparam:    false     # true, if unused parameters should be tolerated
    sloppy:     true      # true, if the 'use strict'; pragma is optional
    stupid:     false     # true, if really stupid practices are tolerated
    sub:        false     # true, if all forms of subscript notation are tolerated
    vars:       true      # true, if multiple var statements per function should be allowed
    white:      true      # true, if sloppy whitespace is tolerated

    maxlen:     150       # the maximum length of a source line
    indent:     2         # the indentation factor
    maxerr:     50        # the maximum number of errors to allow
    passfail:   true     # true, if the scan should stop on first error

    # following are relevant only if undef = false
    browser:    false     # true, if the standard browser globals should be predefined
    rhino:      false     # true, if the Rhino environment globals should be predefined
    windows:    false     # true, if MS Windows-specific globals should be predefined
    widget:     false     # true if the Yahoo Widgets globals should be predefined
    devel:      false     # true, if logging should be allowed (console, alert, etc.)

  predefined:
    # list of predefined elements, comma separated
    # prototypes - "$, $$, $w, $h, $r, $a, $f, prototype, object, effect, event, element, class, form, hash, ajax, try"
    # jquery - "$, jQuery"

scan:
  include:
  - 'public/javascripts/**/*.js'
  - 'app/assets/javascripts/**/*.js'
